### PR TITLE
Support for the raw format

### PR DESCRIPTION
**Pull request by boldt**
This prepares the raw format support for **node-webcrypto-ossl**, as discussed under PeculiarVentures/node-webcrypto-ossl/issues/89

Most comments can be found in the commit e36c1ee

I did not test, if these changes have any influence on [node-webcrypto-ossl](https://github.com/PeculiarVentures/node-webcrypto-ossl), [node-webcrypto-p11](https://github.com/PeculiarVentures/node-webcrypto-p11), and [webcrypto-liner](https://github.com/PeculiarVentures/webcrypto-liner).

### CODE REVIEW

**Comment by rmhrisk** [comment]
@microshine please review

**Comment by rmhrisk** [comment]
@boldt looks good to me, will merge with @microshine's review

**Comment by rmhrisk** [comment]
@boldt can you resolve conflict on this, then I will merge.

**Comment by boldt** [comment]
It should be resolved.

**Comment by rmhrisk** [comment]
@boldt thanks, Ill merge.

**Pull request merged**
